version: "0.0.1"
services:
  spring-boot-app:
    container_name: spring-boot-app
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
